name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #tomar lo q tenemos en el repo
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with: 
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      #para hacer referencia a este paso
      id: version

    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker build Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t franloz/docker-graphql:$NEW_VERSION .
        docker build -t franloz/docker-graphql:latest .

    - name: Docker push Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push franloz/docker-graphql:$NEW_VERSION
        docker push franloz/docker-graphql:latest

    



        
    #name: Build the Docker image
      #: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
