name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #tomar lo q tenemos en el repo
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker build Image
      run: |
        docker build -t franloz/docker-graphql:0.0.2 .
        docker build -t franloz/docker-graphql:latest .

    - name: Docker push Image
      run: |
        docker push franloz/docker-graphql:0.0.2
        docker push franloz/docker-graphql:latest

    



        
    #name: Build the Docker image
      #: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
